services:
  - type: web
    name: medical-rag-backend
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: QDRANT_URL
        value: http://medical-rag-qdrant:6333
      - key: QDRANT_COLLECTION_NAME
        value: medical_docs

  - type: pserv
    name: medical-rag-qdrant
    env: docker
    image:
      url: qdrant/qdrant:latest
    disk:
      name: qdrant-data
      mountPath: /qdrant/storage
      sizeGB: 1
